=== SPinigin/ITMO/HTML.XML_Course/XML/Lab_2/lessons_DTD.dtd
<!ELEMENT lessons (lesson+)>
<!ELEMENT lesson (Name, StartDate, EndDate, Teacher, TeacherPosition)> 
<!ELEMENT Name (#PCDATA)> 
<!ELEMENT StartDate (#PCDATA)> 
<!ELEMENT EndDate (#PCDATA)> 
<!ELEMENT Teacher (#PCDATA)> 
<!ELEMENT TeacherPosition (#PCDATA)>

=== SPinigin/ITMO/HTML.XML_Course/XML/Lab_2/lessons.xml
<?xml version = "1.0" encoding ="utf-8"?>
<!DOCTYPE lessons SYSTEM "lessons_DTD.dtd">
<lessons>
	<lesson id = "CS">
		<Name>Программирование на С#</Name>
		<StartDate>13.04.2023</StartDate>
		<EndDate>4.05.2023</EndDate>
		<Teacher>Осипов Н.А.</Teacher>
		<TeacherPosition>доцент</TeacherPosition>
	</lesson>
	
	<lesson id = "JAVA">
		<Name>Программирование на Java</Name>
		<StartDate>12.10.2023</StartDate>
		<EndDate>14.11.2023</EndDate>
		<Teacher>Харатян А.С.</Teacher>
		<TeacherPosition>старший преподаватель</TeacherPosition>
	</lesson>
	
	<lesson id = "Python">
		<Name>Программирование на Python</Name>
		<StartDate>16.11.2023</StartDate>
		<EndDate>05.12.2023</EndDate>
		<Teacher>Кузьмин К.М.</Teacher>
		<TeacherPosition>старший преподаватель</TeacherPosition>
	</lesson>
</lessons>
